version: '3.3'

services:
  web:
    image: odoo:13.0
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "5678:5678"
    volumes:
      - type: bind
        source: "./payment_multisafepay_official"
        target: "/mnt/extra-addons/payment_multisafepay_official"
    command: ['python','-m','debugpy','--listen','5678','/usr/bin/odoo']
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
    odoo-db-data: